NRAKOProjektWeb/Controllers/PhotosController.cs
using Microsoft.AspNetCore.Authorization;
using Microsoft.AspNetCore.Mvc;
using NRAKOProjektWeb.Interface.Repository;
using NRAKOProjektWeb.Models;
using NRAKOProjektWeb.Patterns.ChainOfResponsibility;
using NRAKOProjektWeb.Patterns.Facade;
using NRAKOProjektWeb.Patterns.MutationFactory;
using NRAKOProjektWeb.Patterns.Singleton;
using NRAKOProjektWeb.ViewModels;
using System;
using System.Collections.Generic;
using System.IO;
using System.Linq;

namespace NRAKOProjektWeb.Controllers
{
    [Authorize]
    public class PhotosController : Controller
    {
        private readonly IUserRepository _userRepository;
        private readonly IPhotoRepository _photoRepository;
        private readonly INRAKOLogger _logger;
        private readonly AmazonS3Tools _amazonS3Tools;
        private readonly IMutationActionFactorySelector _mutationActionFactorySelector;


        public PhotosController(
            IUserRepository userRepository,
            IPhotoRepository photoRepository,
            INRAKOLogger logger,
            AmazonS3Tools amazonS3Tools,
            IMutationActionFactorySelector mutationActionFactorySelector)
        {
            _photoRepository = photoRepository;
            _userRepository = userRepository;
            _logger = logger;
            _amazonS3Tools = amazonS3Tools;
            _mutationActionFactorySelector = mutationActionFactorySelector;
        }

        private NRAKOUser CurrentUser
        {
            get
            {
                return _userRepository.GetUser(HttpContext?.User);
            }
        }
        private bool IsAdmin
        {
            get
            {
                return CurrentUser == null ? false : _userRepository.IsInRole(CurrentUser, "Admin");
            }
        }

        [AllowAnonymous]
        public IActionResult Index()
        {
            ViewBag.ShowFilter = true;
            List<PhotoViewModel> model = new List<PhotoViewModel>();

            string userId = CurrentUser == null ? null : CurrentUser.Id;

            var photos = _photoRepository.GetPhotos();

            model = Helpers.Helpers.GetPhotoViewModelsFromPhotos(photos, userId, IsAdmin).ToList();

            IEnumerable<Photo> photosEnumerable = _photoRepository.PhotoDefaultIfEmpty();

            Helpers.Helpers.SetFilterBounds(photosEnumerable, ViewBag);

            return View(model);
        }

        public IActionResult CreateNewPhoto()
        {
            var userPhotos = _photoRepository.GetphotosByUserID(CurrentUser.Id);

            MaxNumberOfPhotosExceededSubscriptionValidationChecker checker = new MaxNumberOfPhotosExceededSubscriptionValidationChecker();
            checker.SetNext(new DailyUploadLimitExceededSubscriptionValidationChecker());

            SubscriptionModel sm = _userRepository.GetSubscriptionModel(CurrentUser.Id);
            SubscriptionModel uc = new SubscriptionModel()
            {
                DailyUploadLimit = userPhotos.Where(up => up.DateCreated.Date == DateTime.Today).Count(),
                MaxNumberOfPhotos = userPhotos.Count()
            };

            string violation = checker.CheckViolation(sm, uc);

            if (violation != null)
            {
                ViewBag.Violation = violation;
                return View("Violation");
            }

            CreatePhotoViewModel cpvm = new CreatePhotoViewModel();
            cpvm.AvailableFormats = Helpers.Helpers.GetAvailableFormats();

            return View(cpvm);
        }

        [HttpPost]
        public IActionResult CreateNewPhoto(CreatePhotoViewModel model)
        {

            if (!ModelState.IsValid)
            {
                return View();
            }

            Photo photo = _photoRepository.SavePhoto(model, CurrentUser?.Id);

            _logger.Log(CurrentUser?.Id, $"Created a new photo @{photo.Url}");


            return RedirectToAction("Index");
        }

        public IActionResult UserPhotos(string id)
        {

            if (id == null)
            {
                id = CurrentUser.Id;
            }

            var userPhotos = _photoRepository.GetphotosByUserID(id);

            var userPhotosViewModels = Helpers.Helpers.GetPhotoViewModelsFromPhotos(userPhotos, CurrentUser?.Id, IsAdmin);

            return View("Index", userPhotosViewModels);
        }

        public IActionResult EditPhoto(int id)
        {


            Photo photo = _photoRepository.GetphotoByID(id);

            if (photo == null)
            {
                return RedirectToAction("Index");
            }

            if (photo.NRAKOUserId != CurrentUser.Id
                && !(IsAdmin))
            {
                return RedirectToAction("Index");
            }


            EditPhotoViewModel epvm = Helpers.Helpers.GetEditPhotoViewModelFromPhoto(photo);

            return View(epvm);
        }
        [HttpPost]
        public IActionResult EditPhoto(EditPhotoViewModel epvm)
        {

            if (!ModelState.IsValid)
            {
                return View();
            }

            Photo photo = _photoRepository.GetphotoByID(epvm.PhotoId);
            if (photo == null)
            {
                return RedirectToAction("Index");
            }

            if (photo.NRAKOUserId != CurrentUser.Id
                && !(IsAdmin))
            {
                return RedirectToAction("Index");
            }

            photo.DateModified = DateTime.Now;
            photo.Description = epvm.Description;

            string[] hashtags = epvm.Hashtags.Split(' ');

            _photoRepository.RemovePhotoHashTags(photo.Id);

            _photoRepository.AddHashtagsToPhoto(hashtags, photo.Id);

            _logger.Log(CurrentUser.Id, $"Edited photo @{photo.Url}, Description: {photo.Description}, Hashtags: {epvm.Hashtags}");

            return RedirectToAction("Index");
        }

        [AllowAnonymous]
        public IActionResult FilterPhotos(string sizeRange, string widthRange, string heightRange, string hashtagsFilter, string authorFilter)
        {
            ViewBag.ShowFilter = true;


            string userId = CurrentUser == null ? null : CurrentUser.Id;


            IEnumerable<Photo> photos = _photoRepository.FilterData(sizeRange, widthRange, heightRange, hashtagsFilter, authorFilter, ViewBag);

            List<PhotoViewModel> model = Helpers.Helpers.GetPhotoViewModelsFromPhotos(photos
                .ToList(), userId, IsAdmin
                )
                .ToList();

            return View("Index", model);
        }

        public IActionResult DownloadPhoto(int id)
        {
            Photo photo = _photoRepository.GetphotoByID(id);
            if (photo == null)
            {
                return RedirectToAction("Index");
            }

            DownloadPhotoViewModel dpvm = Helpers.Helpers.GetDownloadPhotoViewModelFromPhoto(photo);
            return View(dpvm);
        }

        [HttpPost]
        public IActionResult DownloadPhoto(DownloadPhotoViewModel model)
        {

            IEnumerable<MutationAction> actions = Newtonsoft.Json.JsonConvert.DeserializeObject<IEnumerable<MutationAction>>(model.ActionList);

            var extension = model.OriginalImageExtension;
            if (model.DoConversion)
            {
                extension = model.ConversionExtension;
            }

            byte[] fileBytes = Helpers.Helpers.PerformMutations(model.PhotoUrl, extension, actions, Request, _mutationActionFactorySelector);

            _logger.Log(CurrentUser.Id, $"Downloaded photo with actions: ${model.ActionList} in format: ${extension}");

            return File(fileBytes, "application/force-download", Path.GetFileNameWithoutExtension(model.PhotoUrl) + "." + extension);
        }

    }
}

NRAKOProjektWeb/Views/Shared/_Layout.cshtml
<!DOCTYPE html>
<html>
<head>
    <meta charset="utf-8" />
    <meta name="viewport" content="width=device-width, initial-scale=1.0" />
    <title>@ViewData["Title"] - NRAKOProjektWeb</title>

    <environment include="Development">
        <link rel="stylesheet" href="~/lib/bootstrap/dist/css/bootstrap.css" />
        <link rel="stylesheet" href="//code.jquery.com/ui/1.12.1/themes/base/jquery-ui.css">
        <link rel="stylesheet" href="https://use.fontawesome.com/releases/v5.7.2/css/all.css" integrity="sha384-fnmOCqbTlWIlj8LyTjo7mOUStjsKC4pOpQbqyi7RrhN7udi9RwhKkMHpvLbHG9Sr" crossorigin="anonymous">
    </environment>
    <environment exclude="Development">
        <link rel="stylesheet" href="https://cdnjs.cloudflare.com/ajax/libs/twitter-bootstrap/4.1.3/css/bootstrap.min.css"
              asp-fallback-href="~/lib/bootstrap/dist/css/bootstrap.min.css"
              asp-fallback-test-class="sr-only" asp-fallback-test-property="position" asp-fallback-test-value="absolute"
              crossorigin="anonymous"
              integrity="sha256-eSi1q2PG6J7g7ib17yAaWMcrr5GrtohYChqibrV7PBE="/>
    </environment>
    <link rel="stylesheet" href="~/css/site.css" />
</head>
<body>
    <header>
        <nav class="navbar navbar-expand-sm navbar-toggleable-sm navbar-light bg-white border-bottom box-shadow mb-3">
            <div class="container">
                <a class="navbar-brand" asp-area="" asp-controller="Photos" asp-action="Index">NRAKOProjektWeb</a>
                <button class="navbar-toggler" type="button" data-toggle="collapse" data-target=".navbar-collapse" aria-controls="navbarSupportedContent"
                        aria-expanded="false" aria-label="Toggle navigation">
                    <span class="navbar-toggler-icon"></span>
                </button>
                <div class="navbar-collapse collapse d-sm-inline-flex flex-sm-row-reverse">
                    <partial name="_LoginPartial" />
                    <ul class="navbar-nav flex-grow-1">
                        <li class="nav-item">
                            <a class="nav-link text-dark" asp-area="" asp-controller="Photos" asp-action="Index">Browse Photos</a>
                        </li>
                        @if (this.User.IsInRole("User") || this.User.IsInRole("Admin"))
                        {
                            <li class="nav-item">
                            <a class="nav-link text-dark" asp-area="" asp-controller="Photos" asp-action="UserPhotos">My Photos</a>
                            </li>
                        }
                        @if (this.User.IsInRole("Admin"))
                        {
                            <li class="nav-item">
                                <a class="nav-link text-dark" asp-area="" asp-controller="Admin" asp-action="Index">Admin page</a>
                            </li>
                        }
                    </ul>
                </div>
            </div>
        </nav>
    </header>
    <div class="container">
        <partial name="_CookieConsentPartial" />
        <main role="main" class="pb-3">
            @RenderBody()
        </main>
    </div>

    <footer class="border-top footer text-muted">
        <div class="container">
            &copy; 2019 - NRAKOProjektWeb - <a asp-area="" asp-controller="Home" asp-action="Privacy">Privacy</a>
        </div>
    </footer>

    <environment include="Development">
        <script src="~/lib/jquery/dist/jquery.js"></script>
        <script src="~/lib/bootstrap/dist/js/bootstrap.bundle.js"></script>
        <script src="https://code.jquery.com/ui/1.12.1/jquery-ui.js"></script>
    </environment>
    <environment exclude="Development">
        <script src="https://cdnjs.cloudflare.com/ajax/libs/jquery/3.3.1/jquery.min.js"
                asp-fallback-src="~/lib/jquery/dist/jquery.min.js"
                asp-fallback-test="window.jQuery"
                crossorigin="anonymous"
                integrity="sha256-FgpCb/KJQlLNfOu91ta32o/NMZxltwRo8QtmkMRdAu8=">
        </script>
        <script src="https://cdnjs.cloudflare.com/ajax/libs/twitter-bootstrap/4.1.3/js/bootstrap.bundle.min.js"
                asp-fallback-src="~/lib/bootstrap/dist/js/bootstrap.bundle.min.js"
                asp-fallback-test="window.jQuery && window.jQuery.fn && window.jQuery.fn.modal"
                crossorigin="anonymous"
                integrity="sha256-E/V4cWE4qvAeO5MOhjtGtqDzPndRO1LBk8lJ/PR7CA4=">
        </script>
    </environment>
    <script src="~/js/site.js" asp-append-version="true"></script>

    @RenderSection("Scripts", required: false)
</body>
</html>

NRAKOProjektWeb/Views/Shared/_SubscriptionScriptsPartial.cshtml
@*
    For more information on enabling MVC for empty projects, visit http://go.microsoft.com/fwlink/?LinkID=397860
*@

<script>
        $(function () {

            $('#selectButton').parent().addClass('selected-pricing-model');
            $('#subscriptionModelId').val($('#selectButton').attr('data-id'));


            $('.selectButton').click(function () {
                $('.test').removeClass('selected-pricing-model');
                var id = $(this).attr('data-id');
                $('#subscriptionModelId').val(id);
                $(this).parent().addClass("selected-pricing-model");
            })
        })
</script>